{
  description = "escriba — Rust + tatara-lisp editor, built on the pleme-io GPU stack";

  nixConfig.allow-import-from-derivation = true;

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs?ref=nixos-25.11";
    crate2nix.url = "github:nix-community/crate2nix";
    flake-utils.url = "github:numtide/flake-utils";
    substrate = {
      url = "github:pleme-io/substrate";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { self, nixpkgs, crate2nix, flake-utils, substrate, ... }:
    let
      lib = nixpkgs.lib;

      # ── tatara-lisp rc renderers (preserved from the legacy flake) ─────
      renderTheme = s:
        ''(deftheme :preset "${s.theme}")'';

      renderOptions = s: lib.concatStringsSep "\n" (lib.filter (x: x != "") [
        ''(defoption :name "tabstop"        :value "${toString s.tabWidth}")''
        ''(defoption :name "shiftwidth"     :value "${toString s.tabWidth}")''
        (if s.lineNumbers
         then ''(defoption :name "number"         :value "true")''
         else ''(defoption :name "number"         :value "false")'')
        (if s.relativeNumbers
         then ''(defoption :name "relativenumber" :value "true")''
         else ''(defoption :name "relativenumber" :value "false")'')
        (if s.wrap
         then ''(defoption :name "wrap"           :value "true")''
         else ''(defoption :name "wrap"           :value "false")'')
        (if s.cursorLine
         then ''(defoption :name "cursorline"     :value "true")''
         else ''(defoption :name "cursorline"     :value "false")'')
      ]);

      renderExtraKeybinds = binds:
        lib.concatMapStringsSep "\n" (b:
          ''(defkeybind :mode "${b.mode}" :key "${b.key}" :action "${b.action}"${
            lib.optionalString (b ? description && b.description != "") ''
 :description "${b.description}"''})''
        ) binds;

      renderRc = cfg: ''
        ;; ~/.config/escriba/rc.lisp — generated by home-manager.
        ;; Edits here get overwritten. Change HM `programs.escriba.*` to
        ;; regenerate, or drop extra forms into `extraConfig`.
        ;;
        ;; Loads *after* the binary's bundled blnvim-parity defaults, so
        ;; declarations here override that baseline.

        ${renderTheme cfg.settings}

        ${renderOptions cfg.settings}

        ${lib.optionalString (cfg.extraKeybinds != []) (renderExtraKeybinds cfg.extraKeybinds)}

        ${cfg.extraConfig}
      '';
    in
    (import "${substrate}/lib/rust-workspace-release-flake.nix" {
      inherit nixpkgs crate2nix flake-utils;
    }) {
      toolName = "escriba";
      packageName = "escriba";
      src = self;
      repo = "pleme-io/escriba";

      module = {
        description = "escriba — Rust + tatara-lisp editor (16 def-forms, blnvim-parity defaults)";
        hmNamespace = "programs";

        extraHmOptions = {
          settings = lib.mkOption {
            default = {};
            description = ''
              Structured editor settings. Rendered to tatara-lisp
              `(deftheme …)` and `(defoption …)` forms in the
              generated rc file.
            '';
            type = lib.types.submodule {
              options = {
                theme = lib.mkOption {
                  type = lib.types.enum [ "nord" "gruvbox-dark" "tokyo-night" "catppuccin-mocha" ];
                  default = "nord";
                  description = "Color preset — escriba-lisp `deftheme`.";
                };
                tabWidth = lib.mkOption {
                  type = lib.types.ints.between 1 16;
                  default = 2;
                  description = "Display width of a tab — `defoption :tabstop` / `:shiftwidth`.";
                };
                lineNumbers = lib.mkOption {
                  type = lib.types.bool;
                  default = true;
                  description = "Show the line-number gutter — `defoption :number`.";
                };
                relativeNumbers = lib.mkOption {
                  type = lib.types.bool;
                  default = true;
                  description = "Show relative line numbers — `defoption :relativenumber`.";
                };
                wrap = lib.mkOption {
                  type = lib.types.bool;
                  default = false;
                  description = "Soft-wrap long lines — `defoption :wrap`.";
                };
                cursorLine = lib.mkOption {
                  type = lib.types.bool;
                  default = true;
                  description = "Highlight the cursor line — `defoption :cursorline`.";
                };
              };
            };
          };

          extraKeybinds = lib.mkOption {
            type = lib.types.listOf (lib.types.submodule {
              options = {
                mode = lib.mkOption {
                  type = lib.types.enum [ "normal" "insert" "visual" "visual-line" "command" ];
                  default = "normal";
                };
                key = lib.mkOption { type = lib.types.str; };
                action = lib.mkOption { type = lib.types.str; };
                description = lib.mkOption { type = lib.types.str; default = ""; };
              };
            });
            default = [];
            description = ''
              Additional keybindings rendered as `(defkeybind …)` forms.
              These override bundled-default bindings on collision.
            '';
          };

          extraConfig = lib.mkOption {
            type = lib.types.lines;
            default = "";
            description = ''
              Additional tatara-lisp appended verbatim to the generated
              `~/.config/escriba/rc.lisp`. Use this for def-forms the HM
              surface doesn't model directly (`defplugin`, `defhighlight`,
              `defhook`, `defsnippet`, etc.).
            '';
          };

          noDefaults = lib.mkOption {
            type = lib.types.bool;
            default = false;
            description = ''
              Pass `--no-defaults` by aliasing `escriba` to skip the
              bundled blnvim-parity rc. Only the generated rc + extras
              apply. Most users should leave this off.
            '';
          };
        };

        extraHmConfig = cfg: {
          home.file.".config/escriba/rc.lisp".text = renderRc cfg;

          home.sessionVariables = {
            ESCRIBARC = "$HOME/.config/escriba/rc.lisp";
          } // lib.optionalAttrs cfg.noDefaults {
            ESCRIBA_NO_DEFAULTS = "1";
          };
        };
      };
    };
}
