{ self }:
{ config, lib, pkgs, ... }:

let
  cfg = config.programs.escriba;
  inherit (lib) mkEnableOption mkOption mkIf types concatMapStringsSep optionalString;

  escribaPkg =
    if cfg.package != null then cfg.package
    else self.packages.${pkgs.stdenv.hostPlatform.system}.default;

  # Render the HM settings submodule into tatara-lisp forms that match
  # `escriba-lisp`'s current surface. Everything here *overrides* the
  # bundled `blnvim-defaults.lisp` that the binary loads first, so users
  # only need to declare what they want changed.
  renderTheme = s:
    ''(deftheme :preset "${s.theme}")'';

  renderOptions = s: lib.concatStringsSep "\n" (lib.filter (x: x != "") [
    ''(defoption :name "tabstop"        :value "${toString s.tabWidth}")''
    ''(defoption :name "shiftwidth"     :value "${toString s.tabWidth}")''
    (if s.lineNumbers
     then ''(defoption :name "number"         :value "true")''
     else ''(defoption :name "number"         :value "false")'')
    (if s.relativeNumbers
     then ''(defoption :name "relativenumber" :value "true")''
     else ''(defoption :name "relativenumber" :value "false")'')
    (if s.wrap
     then ''(defoption :name "wrap"           :value "true")''
     else ''(defoption :name "wrap"           :value "false")'')
    (if s.cursorLine
     then ''(defoption :name "cursorline"     :value "true")''
     else ''(defoption :name "cursorline"     :value "false")'')
  ]);

  renderExtraKeybinds = binds:
    concatMapStringsSep "\n" (b:
      ''(defkeybind :mode "${b.mode}" :key "${b.key}" :action "${b.action}"${
        optionalString (b ? description && b.description != "") ''
 :description "${b.description}"''})''
    ) binds;

  renderRc = s: ''
    ;; ~/.config/escriba/rc.lisp — generated by home-manager.
    ;; Edits here get overwritten. Change HM `programs.escriba.*` to
    ;; regenerate, or drop extra forms into `extraConfig`.
    ;;
    ;; Loads *after* the binary's bundled blnvim-parity defaults, so
    ;; declarations here override that baseline.

    ${renderTheme s}

    ${renderOptions s}

    ${lib.optionalString (cfg.extraKeybinds != []) (renderExtraKeybinds cfg.extraKeybinds)}

    ${cfg.extraConfig}
  '';

in
{
  options.programs.escriba = {
    enable = mkEnableOption "escriba — Rust + tatara-lisp editor (16 def-forms, blnvim-parity defaults)";

    package = mkOption {
      type = types.nullOr types.package;
      default = null;
      description = ''
        Override the escriba package. Defaults to the flake's own
        build via `self.packages.<system>.default`.
      '';
    };

    # High-level settings surface. Every field here renders to a real
    # escriba-lisp def-form so the generated rc integrates cleanly
    # with hand-written additions via `extraConfig` / `extraKeybinds`.
    settings = mkOption {
      default = {};
      description = ''
        Structured editor settings. Rendered to tatara-lisp
        `(deftheme …)` and `(defoption …)` forms in the
        generated rc file.
      '';
      type = types.submodule {
        options = {
          theme = mkOption {
            type = types.enum [ "nord" "gruvbox-dark" "tokyo-night" "catppuccin-mocha" ];
            default = "nord";
            description = "Color preset — escriba-lisp `deftheme`.";
          };
          tabWidth = mkOption {
            type = types.ints.between 1 16;
            default = 2;
            description = "Display width of a tab — `defoption :tabstop` / `:shiftwidth`.";
          };
          lineNumbers = mkOption {
            type = types.bool;
            default = true;
            description = "Show the line-number gutter — `defoption :number`.";
          };
          relativeNumbers = mkOption {
            type = types.bool;
            default = true;
            description = "Show relative line numbers — `defoption :relativenumber`.";
          };
          wrap = mkOption {
            type = types.bool;
            default = false;
            description = "Soft-wrap long lines — `defoption :wrap`.";
          };
          cursorLine = mkOption {
            type = types.bool;
            default = true;
            description = "Highlight the cursor line — `defoption :cursorline`.";
          };
        };
      };
    };

    extraKeybinds = mkOption {
      type = types.listOf (types.submodule {
        options = {
          mode = mkOption {
            type = types.enum [ "normal" "insert" "visual" "visual-line" "command" ];
            default = "normal";
          };
          key = mkOption { type = types.str; };
          action = mkOption { type = types.str; };
          description = mkOption { type = types.str; default = ""; };
        };
      });
      default = [];
      description = ''
        Additional keybindings rendered as `(defkeybind …)` forms.
        These override bundled-default bindings on collision.
      '';
    };

    extraConfig = mkOption {
      type = types.lines;
      default = "";
      description = ''
        Additional tatara-lisp appended verbatim to the generated
        `~/.config/escriba/rc.lisp`. Use this for def-forms the HM
        surface doesn't model directly (`defplugin`, `defhighlight`,
        `defhook`, `defsnippet`, etc.).
      '';
    };

    noDefaults = mkOption {
      type = types.bool;
      default = false;
      description = ''
        Pass `--no-defaults` by aliasing `escriba` to skip the
        bundled blnvim-parity rc. Only the generated rc + extras
        apply. Most users should leave this off.
      '';
    };
  };

  config = mkIf cfg.enable {
    home.packages = [ escribaPkg ];

    # Home-manager renders the config into $XDG_CONFIG_HOME/escriba/
    # so the binary's default rc path resolution finds it without
    # needing $ESCRIBARC override.
    home.file.".config/escriba/rc.lisp".text = renderRc cfg.settings;

    # Session env — binary already falls back to ~/.config/escriba/rc.lisp
    # but setting ESCRIBARC makes the resolution explicit + survives
    # users who XDG_CONFIG_HOME elsewhere.
    home.sessionVariables = {
      ESCRIBARC = "${config.home.homeDirectory}/.config/escriba/rc.lisp";
    } // lib.optionalAttrs cfg.noDefaults {
      ESCRIBA_NO_DEFAULTS = "1";
    };
  };
}
