{ self }:
{ config, lib, pkgs, ... }:

let
  cfg = config.programs.escriba;
  inherit (lib) mkEnableOption mkOption mkIf types;

  escribaPkg =
    if cfg.package != null then cfg.package
    else self.packages.${pkgs.stdenv.hostPlatform.system}.default;

  renderLisp = settings: ''
    ;; ~/.config/escriba/escriba.lisp — generated by home-manager.
    ;; Edit your HM config (programs.escriba.settings.*) to regenerate.

    (defescriba
      :tema               "${settings.theme}"
      :largura-tab        ${toString settings.tabWidth}
      :numeros-linha      ${if settings.lineNumbers then "#t" else "#f"}
      :mostrar-statusline ${if settings.statusline then "#t" else "#f"}
      :modo-inicial       "${settings.initialMode}"
      :render             "${settings.render}")
  '';

  generatedConfig = pkgs.writeText "escriba.lisp" (renderLisp cfg.settings);

in
{
  options.programs.escriba = {
    enable = mkEnableOption "escriba — Rust/tatara-lisp editor";

    package = mkOption {
      type = types.nullOr types.package;
      default = null;
      description = "Override the escriba package. Defaults to the flake's own build.";
    };

    settings = mkOption {
      type = types.submodule {
        options = {
          theme = mkOption {
            type = types.str;
            default = "nord";
            description = "Color theme — Nord by default.";
          };
          tabWidth = mkOption {
            type = types.int;
            default = 2;
            description = "Display width of a tab character.";
          };
          lineNumbers = mkOption {
            type = types.bool;
            default = true;
            description = "Show absolute line numbers in the gutter.";
          };
          statusline = mkOption {
            type = types.bool;
            default = true;
            description = "Render the bottom status line.";
          };
          initialMode = mkOption {
            type = types.enum [ "normal" "insert" "visual" "command" ];
            default = "normal";
            description = "Mode escriba starts in.";
          };
          render = mkOption {
            type = types.enum [ "gpu" "tui" "text" ];
            default = "tui";
            description = "Default render backend: gpu (madori), tui (ratatui), or text.";
          };
        };
      };
      default = {};
      description = "Declarative escriba config — rendered to tatara-lisp and loaded via shikumi.";
    };

    extraConfig = mkOption {
      type = types.lines;
      default = "";
      description = "Additional tatara-lisp appended verbatim to escriba.lisp.";
    };
  };

  config = mkIf cfg.enable {
    home.packages = [ escribaPkg ];

    home.file.".config/escriba/escriba.lisp" = {
      text = (renderLisp cfg.settings) + cfg.extraConfig;
    };
  };
}
