{ self }:
{ config, lib, pkgs, ... }:

let
  cfg = config.programs.escriba;
  inherit (lib) mkEnableOption mkOption mkIf types;
  pkg =
    if cfg.package != null then cfg.package
    else self.packages.${pkgs.stdenv.hostPlatform.system}.default;
in
{
  options.programs.escriba = {
    enable = mkEnableOption "escriba — Rust + tatara-lisp editor, built on the pleme-io GPU stack";

    package = mkOption {
      type = types.nullOr types.package;
      default = null;
      description = "Override the default package.";
    };

    theme = mkOption {
      type = types.str;
      default = "nord";
      description = "Color theme — Nord by default.";
    };

    tabWidth = mkOption {
      type = types.int;
      default = 2;
      description = "Display width of a tab character.";
    };

    lineNumbers = mkOption {
      type = types.bool;
      default = true;
      description = "Show absolute line numbers in the gutter.";
    };

    statusline = mkOption {
      type = types.bool;
      default = true;
      description = "Render the bottom status line.";
    };

    initialMode = mkOption {
      type = types.enum [ "normal" "insert" "visual" "command" ];
      default = "normal";
      description = "Mode escriba starts in.";
    };

    render = mkOption {
      type = types.enum [ "gpu" "tui" "text" ];
      default = "tui";
      description = "Default render backend.";
    };

  };

  config = mkIf cfg.enable {
    home.packages = [ pkg ];

    home.file.".config/escriba/escriba.lisp".text = let
      renderLisp = settings: ''
        ;; ~/.config/escriba/escriba.lisp — generated by home-manager.
        (defescriba
          :theme "${cfg.theme}"
          :tab-width ${toString cfg.tabWidth}
          :line-numbers ${if cfg.lineNumbers then "#t" else "#f"}
          :statusline ${if cfg.statusline then "#t" else "#f"}
          :initial-mode "${cfg.initialMode}"
          :render "${cfg.render}")
      '';
    in renderLisp cfg;

    home.sessionVariables = {
      ESCRIBA_CONFIG = "${config.home.homeDirectory}/.config/escriba/escriba.lisp";
    };
  };
}
